### PR TITLE
Improve Makefiles

### PR DESCRIPTION
**Pull request by e-kwsm**
* use `CPPFLAGS`, and `AR` and `ARFLAGS`
  https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
* replace `smash.a` with `libsmash.a`
* use `-I` for Fortran module file directory

### CODE REVIEW

**Comment by ishimura** [comment]
Thank you for your commit, but modified Makefiles generate mod files in the smash directory, not in the smash/obj. 
The develop-3.0.0 branch has been merged into the master branch.

**Comment by e-kwsm** [comment]
> Thank you for your commit, but modified Makefiles generate mod files in the smash directory, not in the smash/obj.

I’ve fixed. Would you reopen?

**Comment by ishimura** [comment]
SMASH-3.0.0 has been already released.
https://sourceforge.net/projects/smash-qc/files/

**Comment by e-kwsm** [comment]
If open, the target branch can be changed.

**Comment by ishimura** [comment]
The smash.a file has been used by others, so it is impossible to change the name right now.
I'll add CPPFLAGS to makefiles after a new branch is created.

**Pull request closed without merging**
